// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTecnicaP2.DataAccess;

#nullable disable

namespace PruebaTecnicaP2.DataAccess.Migrations
{
    [DbContext(typeof(ProyectoContext))]
    [Migration("20230123013025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("PruebaTecnicaP2.Models.Entities.Puntos", b =>
                {
                    b.Property<int>("PuntosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("factura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("id_comercio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_sucursal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_transaccion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("uid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("uid_cms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("PuntosId");

                    b.ToTable("Puntos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
